### ISSUE TITLE
Remove `final` from the `DefaultConsumer`

### ISSUE THREAD

**Issue by caseyamcl** [AgencyPMG/Queue#14]
Why does the `DefaultConsumer` use the final keyword?  This makes it difficult to re-use the code in this class (for example, adding event dispatching, or counting the number of jobs)?

I suggest removing it can be re-used without rewriting all of the fine error-handling logic.

**Comment by chrisguitarguy** [comment]
Here are a few articles that influenced my thinking on this:

- http://verraes.net/2014/05/final-classes-in-php/
- http://ocramius.github.io/blog/when-to-declare-classes-final/

I agree that the error handling stuff is painful right now with more than one consumer, but I'm not sure removing `final` is the answer. The `DefaultConsumer` uses other abstractions (like the `Executor` etc) from this library, but there's no saying another consumer implementation has to do that.

Exposing the `safeOnce` method in the `Consumer` interface, for instance, would mean the examples you gave (event dispatching, etc) could be easily added with decorators. Or even just putting out an abstract base class for consumers.

Anyway, I'll think on it, and figure out something that will work here. I ran into the same sort of issues trying to figure out something for #12

**Comment by chrisguitarguy** [comment]
Hey @caseyamcl, really sorry for the delay here, but I do have a solution for you that's going to be merged in a bit.

In v3.0 of this library, `DefaultConsumer::once` is going to be safe to run in a loop, and generally implementations of `Consumer` should be have their `once` methods be safe to run in a loop too. there's also a new `AbstractConsumer` class. So say you want to to count jobs...


```php
use Psr\Log\LogggerInterface;
use PMG\Queue\Consumer;
use PMG\Queue\AbstractConsumer;

final class JobCountingConsumer extends AbstractConsumer
{
  private $count = 0;
  /** @var Consumer */
  private $wrapped;
  /** @var LoggerInterface */
  private $logger;

  public function __construct(Consumer $wrapped, LoggerInterface $logger=null)
  {
    parent::__construct($logger);
    $this->wrapped = $wrapped;
  }

  public function once($queueName)
  {
    $this->count++;
    return $this->wrapped->once($queueName);
  }
}
```

Pass an instance of `DefaultConsumer` (or a custom implementation, etc) to the constructor of the counting consumer.
