### ISSUE TITLE
PcntlForkingHandler issue

### ISSUE THREAD

**Issue by eddy8** [AgencyPMG/Queue#46]
https://github.com/AgencyPMG/Queue/blob/master/src/Handler/PcntlForkingHandler.php#L50

if you do not catch exception here, the child process will never have a chance to execute exit statement($this->pcntl->quit($result)) if an exception is thrown. the child process will fork new child process to handle message and lots of process will be forked again.

**Comment by chrisguitarguy** [comment]
Ah, I see what you mean. It will propagate all the way up to the consumer where it's caught and dealt with and then it re-enters the loop.

Whoops! Will address it today.
