### ISSUE TITLE
Consider using queue interprop as abstraction for queues

### ISSUE THREAD

**Issue by makasim** [AgencyPMG/Queue#82]
Hello!

Please look at https://github.com/queue-interop/queue-interop project. Using interfaces from it allows us reuse some implementations like enqueue, which supports a lot of transports. You can outsource some code

**Comment by chrisguitarguy** [comment]
Once it's 1.0, maybe!

Looking at it, the architecture the interop implies is quite a bit different from what we've built in the queue library here. I'll need to dig in a bit and see if it makes sense.
